# Dependencies
markdown:         kramdown
highlighter:      rouge

gems: 		     [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        /blog/:categories/:year/:month/:day/:title/

# Setup
title:            Manas Chaudhari
tagline:          ''
description:      ''
url:              http://manas-chaudhari.github.io
baseurl:          /

author:
  name:           'Manas Chaudhari'
  url:            https://twitter.com/ChaudhariManas

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/manas-chaudhari/manas-chaudhari.github.io


# Collections
collections:
- projects

# Google Analytics
google_analytics: UA-82758741-1
